### ISSUE TITLE
Add a "Pointer" Tool to Deselect the "Copy Shape Format" Tool

### ISSUE THREAD

**Issue by gyanl** [prikhi/pencil#694]
The only way to exit format painter seems to be to click on one of the other tool options like zoom in/out. Adding a 'pointer' tool to the toolbar seems like a good idea.

**Comment by prikhi** [comment]
Not sure what you mean by `painter`. Do you mean the color selection tool? If not, can you please clarify or give instructions on how to reproduce this behavior.

If you mean the color selection tool, that can be exited by pressing your `Escape` key.

**Comment by gyanl** [comment]
The tool is called format painter in MS Office, so I though it was called that. The tooltip text calls it "Copy shape format." (It's the one shaped like a brush)
Steps to reproduce : I was working on an Android app UI, and the entire canvas was filled with a background shape. After I used the "Copy shape format" tool, I couldn't figure out how to turn it off and return to the regular pointer. 
It's not an issue for projects without a background shape as clicking on a blank/empty area turns it off and returns to the pointer. 

It can be exited using Esc though, which I tried after you suggested it.

**Comment by prikhi** [comment]
The escape key is commonly used throughout the app to "escape" from things like nav menus, text boxes, dropdowns, popups, etc. 

I'm gonna say this isn't really worth it right now because it'd be a button just to deselect the "Copy Shape Format" tool. It would be useful if we add more tools where the click action is replaced.
