### ISSUE TITLE
package name under ubuntu is taken by other package already

### ISSUE THREAD

**Issue by jdittrich** [prikhi/pencil#748]
**What I did:**  Build the .deb of the  .14 Version and wanted to install it. 
**What happened:** The installer showed that a previous version of the program of the app is already in the repositories. This is true (there is an evoluspencil-package) but the app refered too (pencil) is a 2D animation tool. If I have that (_pencil_ 2D animation) installed and I install the pencil-prototoyping tool, they will be in conflict. 
**What should happen instead:** The build for Ubuntu (and other linux systems) should be called differently. I assume we should not use _evolus_pencil, but we could use _pencilmockup_, _pencilprototyping_ or the like

**Comment by dagomar** [comment]
I have the same problem, and when I try to install this pencil, I get error messages (not sure if that is related though). Hit me up if you need more info!

**Comment by jasiralavi** [comment]
There seems to be 2 versions of the other pencil (cartoon) software.
The newer one is called pencil2d now so that is not conflicting now with pencil-prototyping.
But the repos still have the old pencil cartoon software as well. That's still called 'pencil'. That's conflicting with the pencil-prototyping.
Below screenshots should help.
![selection_037](https://cloud.githubusercontent.com/assets/16372030/12184042/d9a57ac4-b5b8-11e5-9e4d-ad216f872447.png)
![workspace 1_038](https://cloud.githubusercontent.com/assets/16372030/12184317/89ad3104-b5ba-11e5-9183-9244bd8d28e2.png)
![workspace 1_039](https://cloud.githubusercontent.com/assets/16372030/12184327/93471cac-b5ba-11e5-924b-c8fda4a171f9.png)

**Comment by parthlawate** [comment]
This PR soves this issue atleast for Ubuntu . please test https://github.com/prikhi/pencil/pull/781
