### ISSUE TITLE
Let Pencil get signed by Firefox

### ISSUE THREAD

**Issue by Mannshoch** [prikhi/pencil#749]
In a future version of Firefox Pencil will not anymore work. 
Please let it get signed from Mozilla.

**Comment by prikhi** [comment]
Thanks, been holding out hoping the old author would get back to me about taking over the extension already on the AMO but I'll probably cave now.

**Comment by Mannshoch** [comment]
Firefox 43 will made problem on Add-ons which are not signed.
Couldn't you do this? Is there a License Problem behind this?

How Compartible would Pencil be with the Future Addon System of Firefox?
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

**Comment by prikhi** [comment]
Awaiting validation:
https://addons.mozilla.org/en-US/firefox/addon/pencil-prototyping/

If mozilla truly deprecates XUL, pencil will die unless it is re-written using the WebExtensions API - provided the API can actually provide equivalent functionality of XUL...

**Comment by Mannshoch** [comment]
Great! 

Thank you.

**Comment by prikhi** [comment]
Thanks for bumping this and reminding me :)

**Comment by prikhi** [comment]
Reopening this because at the rate that mozilla is approving plugins, it will take a year and a half for Pencil to be reviewed & signed... We are number 144 in the queue and haven't moved since I uploaded 3 days ago...

I think the solution will be to keep that in the review queue and also upload an unlisted XPI that can be distributed via the github releases page. Unlisted addons get signed immediately so that would allow installation once FF hits v44(where I believe the ability to install unsigned plugins will be removed).

**Comment by jasiralavi** [comment]
Unlisted XPI would require users to modify the firefox configurations to allow their installation. It can potentially open the door for other bad stuff to enter. I think a better strategy would be to upload and let the AMO approve newer versions of Pencil at their pace, and focus more on getting people to install the standalone version to have the latest and greatest.

I'm sure all serious users prefer a standalone version instead of having to depend on firefox to run the application. Some of the reasons being:
1. Pencil is a complete application having nothing to do with browsing (firefox activity)
2. A standalone version eliminates need to open firefox to then launch pencil
3. Currently (in linux, not sure of other OS) pencil window is grouped together in the firefox (a firefox icon is shown) this affects the ability to easily switch between tasks.

**Comment by alexandreleroux** [comment]
@jasiralavi for some of us, there's still immense value to Pencil as a Firefox plugin. In my case, we can't install any software at work, but Firefox plugins are allowed. It's the only way we can access Pencil, so 'Pencil in Firefox' does matter to some of the 'serious users' :-) Cheers -- Alex

**Comment by prikhi** [comment]
Unlisted XPIs are uploaded to AMO, just not shown in their addons directory, and thus are immediately signed instead of having to wait for approval.

But thanks to Noitidart, the listed Pencil addon has been approved early and can be installed without disabled the signature requirements:
https://addons.mozilla.org/en-US/firefox/addon/pencil-prototyping/
